### ISSUE TITLE
NSClient++ installer URLs broken, like with salt-winrepo

### ISSUE THREAD

**Issue by ArthurMeneau** [saltstack/salt-winrepo-ng#246] opened 2016-01-15 02:22 UTC
This is almost identical to issue saltstack/salt-winrepo#586 and pull request saltstack/salt-winrepo#587

I will provide a pull request for this shortly.

**Comment by b18** [comment] 2016-01-15 02:55
Didn't see this issue, but just submitted a pull request for this on the winrepo-ng repo, so disregard if you submit one as well.

**Comment by ameneau-xetus** [comment] 2016-01-15 17:33
Thanks @b18, 

@TheBigBear looks like this issue was resolved with pull request #247

**Comment by moebiuseye** [comment] 2016-03-27 13:41
Confirmed. This issue should be closed now.

**Closed** 2016-04-07 15:56 UTC
